# めあて： axial, coronal, sagittalをつなげよう！

In [1]:
# 各々のdicomを読み込む
import pydicom

axial_dcm = pydicom.read_file("dataset/negative/axial/1.2.392.200036.9142.10002202.1020330992.3.20190507181142.96405/DicomFile.dcm")
# "dataset/negative/patient_id/axial/slice_num/DicomFile.dcm" とすることが望ましい．

coronal_dcm = pydicom.read_file("dataset/negative/coronal/1.2.392.200036.9142.10002202.1020330992.3.20190507181141.96351/DicomFile.dcm")
sagittal_dcm = pydicom.read_file("dataset/negative/sagital/1.2.392.200036.9142.10002202.1020330992.3.20190507181142.96578/DicomFile.dcm")

In [6]:
# ピクセルデータを読み込む
axial_arr = axial_dcm.pixel_array
coronal_arr = coronal_dcm.pixel_array
sagittal_arr = coronal_dcm.pixel_array # sagittalのサイズが長方形になっちゃってるので，coronalを仮に入れておく．ミスではない．

In [7]:
# サイズが揃っていることを確認
print(axial_arr.shape, coronal_arr.shape, sagittal_arr.shape)

(640, 640) (640, 640) (640, 640)


結合するには，numpy.concatenate(), numpy.stack(), numpy.block(), numpy.vstack(), numpy.hstack()などを使うらしい．<br> ちがいはよく分からないが...今回は縦に繋げたいので，vstack()を使う．

In [16]:
import numpy as np
concat = np.stack([axial_arr, coronal_arr, sagittal_arr], 0)
concat.shape

(3, 640, 640)

np.stack()を使うのが良さそう！ <br> 
np.stack([a, b, c], 何番目に軸を追加するか指定)

In [2]:
import sklearn
from sklearn.model_selection import KFold

In [3]:
paths = ["a", "b", "c", "d", "e"]
kf = KFold(n_splits=3)
kf.get_n_splits(paths)

3

In [5]:
for train, test in kf.split(paths):
    print(train, test)

[2 3 4] [0 1]
[0 1 4] [2 3]
[0 1 2 3] [4]
